#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

cd "$ROOT"

# https://stackoverflow.com/a/61417700

RUSTDOCFLAGS="--cfg docsrs" \
cargo +nightly doc --all-features --package=read-url --no-deps --open
