#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

cd "$ROOT"

if [ "$TARGET" == release ]; then
	m 'building binaries (release)...' "$CYAN"
	cargo install --path="$ROOT/cli"
else
	m 'building binaries (dev)...' "$CYAN"
	cargo install --path="$ROOT/cli" --debug
fi
